server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/TEACHING?useUnicode=true&characterEncoding=UTF-8
    username: jw_admin
    password: oracle123
    driver-class-name: oracle.jdbc.OracleDriver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: input
